version: '3'
services:
  backend:
    image: 'natibloy/attendance-project:latest'
    #ports: 
      #- "5000:5000"
    restart: always
    env_file:
      - environmentals/.env
    depends_on:
      - mysql
    #expose:
      #- 5000
  
  mysql:
    image: 'mysql:latest'
    env_file:
      - environmentals/.env
    restart: always

  frontend:
    image: 'natibloy/attendance-frontend:latest'
    #ports:
      #- "3000:80"
    #links:
      #- backend
  
  nginx:
    image: 'natibloy/attendance-nginx:latest'
    restart: always
    ports:
      - '3050:80'