version: '3'
services:
  backend:
    image: 'amitlubin/attendance-backend:latest'
    ports: 
      - "5000:5000"
    restart: always
    env_file:
      - environmentals/.env
    depends_on:
      - mysql
  
  mysql:
    image: 'mysql:latest'
    env_file:
      - environmentals/.env
    restart: always

  frontend:
    image: 'amitlubin/attendance-frontend:latest'
    depends_on:
      - backend
    ports:
      - "3000:80"