version: '3'
services:
  backend:
    image: 'natibloy/attendance-project:latest'
    restart: always
    env_file:
      - environmentals/.env
    depends_on:
      - mysql
    expose:
  
  mysql:
    image: 'mysql:latest'
    env_file:
      - environmentals/.env
    restart: always

  frontend:
    image: 'natibloy/attendance-frontend:latest'

  nginx:
    image: 'natibloy/attendance-nginx:latest'
    ports:
      - '3050:80'